// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

import { Reminder } from ".";

/*
All of these responses where generated by GPT using a prompt similar to:

```
Here's a JavaScript string literal template:

`I couldn't find a ${item} on your ${list} list.`

Create a JavaScript array with 7 variations of the template.
The variations should be helpful, creative, clever, and very friendly.
The variations should always use the back tick `` syntax.
The variations should always include ${item} and ${list} variables.
```

7 variations were asked for so that we can remove the 2 we like the least.
*/

/**
 *
 */
export function greeting(): string {
    return getRandomResponse([
        'Welcome to List Bot! Type /reset to delete all existing lists.',
        "Hello! I'm List Bot. Use /reset to delete all your lists.",
        "Hi there! I'm here to help you manage your lists. Use /reset to delete all lists.",
        "Greetings! I'm List Bot. Type /reset to delete all your list.",
        'Hey there! List Bot here. You can use /reset to delete all lists.'
    ]);
}

export function reset(): string {
    return getRandomResponse([
        'Resetting all the reminders',
    ]);
}

export function reminderNotFound(): string {
    return getRandomResponse([
        `I'm sorry, I couldn't locate the reminder.`,
    ]);
}


export function cancelReminder(index: number): string {
    return getRandomResponse([
        `Sucessfully cancelled reminder number ${index}`
    ])
}

export function listReminders(remindersList: string): string {
    return getRandomResponse([
        `Here's a list of the current reminders:\n\n\n ${remindersList}`
    ])
}

export function cannotParseDate(): string {
    return getRandomResponse([
        `Sorry, I couldn't understand when you want to set the reminder for.`
    ])
}

export function dateIsInThePast(): string {
    return getRandomResponse([
        `Sorry, The reminder date is in the past. Please set a reminder date for the future.`
    ])
}


/**
 * @param action
 */
export function unknownAction(action: string): string {
    return getRandomResponse([
        `I'm sorry, I'm not sure how to ${action}.`,
        `I don't know the first thing about ${action}.`,
        `I'm not sure I'm the best person to help with ${action}.`,
        `I'm still learning about ${action}, but I'll try my best.`,
        `I'm afraid I'm not experienced enough with ${action}.`
    ]);
}

/**
 * @param responses
 */
function getRandomResponse(responses: string[]): string {
    const i = Math.floor(Math.random() * (responses.length - 1));
    // eslint-disable-next-line security/detect-object-injection
    return responses[i];
}
